export const Galleries = [{
    'galleryId': '1',
    'title': 'Alesund',
    'dateCreated': '2024-08-14T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/Alesund.jpg',
    'description': 'Przyjemny lot samolotem.',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '2',
    'title': 'Gdańsk',
    'dateCreated': '2023-12-07T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/Gdansk.jpg',
    'description': 'Spacer.',
    'tags': [],
    'photos': [],
},{
    'galleryId': '3',
    'title': 'Kłodawa',
    'dateCreated': '2025-02-12T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/Kłodawa.jpg',
    'description': 'Bardzo ładny kościół.',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '4',
    'title': 'Skarszewy',
    'dateCreated': '2025-03-23T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/Skarszewy.jpg',
    'description': 'Piękne miasto.',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '5',
    'title': 'Starogard Gdański',
    'dateCreated': '2025-03-24T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/StarogardGD.jpg',
    'description': 'Fajne takie.',
    'tags': [],
    'photos': [],
}, {
    'galleryId': '6',
    'title': 'Ulsteivnik',
    'dateCreated': '2024-08-03T00:00:00+00:00',
    'thumbUrl': 'gallery/assets/img/Ulsteivnik.jpg',
    'description': 'Dużo wody.',
    'tags': [],
    'photos': [],
}]